// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6X3Q13egKV_NKr95t7yLNOVJ5z5xgveE',
    appId: '1:605950038024:web:5ba6e4420df2bd080381bd',
    messagingSenderId: '605950038024',
    projectId: 'twitter-clone-harry',
    authDomain: 'twitter-clone-harry.firebaseapp.com',
    storageBucket: 'twitter-clone-harry.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiNpNQ1Anq9Eg53nzyBa3bXpf5zNfnZys',
    appId: '1:605950038024:android:609ec23cbbd6239b0381bd',
    messagingSenderId: '605950038024',
    projectId: 'twitter-clone-harry',
    storageBucket: 'twitter-clone-harry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0t05i8bttCrYHVZZic7VSwZvGlJ8gO_8',
    appId: '1:605950038024:ios:e17a176fb7716a8c0381bd',
    messagingSenderId: '605950038024',
    projectId: 'twitter-clone-harry',
    storageBucket: 'twitter-clone-harry.firebasestorage.app',
    iosBundleId: 'com.harryapps.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0t05i8bttCrYHVZZic7VSwZvGlJ8gO_8',
    appId: '1:605950038024:ios:e17a176fb7716a8c0381bd',
    messagingSenderId: '605950038024',
    projectId: 'twitter-clone-harry',
    storageBucket: 'twitter-clone-harry.firebasestorage.app',
    iosBundleId: 'com.harryapps.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6X3Q13egKV_NKr95t7yLNOVJ5z5xgveE',
    appId: '1:605950038024:web:f27c9f5d4c7d6a3b0381bd',
    messagingSenderId: '605950038024',
    projectId: 'twitter-clone-harry',
    authDomain: 'twitter-clone-harry.firebaseapp.com',
    storageBucket: 'twitter-clone-harry.firebasestorage.app',
  );
}
