// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxNrSuU0pczgWQneQGZstKb_ZDfXSm4gw',
    appId: '1:706563876040:web:bcc585c5ea65c12db4b1fd',
    messagingSenderId: '706563876040',
    projectId: 'twitter-us-4',
    authDomain: 'twitter-us-4.firebaseapp.com',
    storageBucket: 'twitter-us-4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdNZvO15zNXj53dr09ZyWiI2kJN-pWhw4',
    appId: '1:706563876040:android:4556b69b10fca5cfb4b1fd',
    messagingSenderId: '706563876040',
    projectId: 'twitter-us-4',
    storageBucket: 'twitter-us-4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbPCn9jZdRJZzHid5wGb8_jYjwVTh2lZI',
    appId: '1:706563876040:ios:6d08fcbfc2123b1fb4b1fd',
    messagingSenderId: '706563876040',
    projectId: 'twitter-us-4',
    storageBucket: 'twitter-us-4.firebasestorage.app',
    iosBundleId: 'com.harryapps.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbPCn9jZdRJZzHid5wGb8_jYjwVTh2lZI',
    appId: '1:706563876040:ios:6d08fcbfc2123b1fb4b1fd',
    messagingSenderId: '706563876040',
    projectId: 'twitter-us-4',
    storageBucket: 'twitter-us-4.firebasestorage.app',
    iosBundleId: 'com.harryapps.twitterClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxNrSuU0pczgWQneQGZstKb_ZDfXSm4gw',
    appId: '1:706563876040:web:97d18596cefac095b4b1fd',
    messagingSenderId: '706563876040',
    projectId: 'twitter-us-4',
    authDomain: 'twitter-us-4.firebaseapp.com',
    storageBucket: 'twitter-us-4.firebasestorage.app',
  );

}